import create from 'zustand'

export const channelStore = create((set) => ({
    channels: [
        {
            'id': 48,
            'channel_id': 48,
            'domain': 'improve',
            'name': '샌드위치 개선사항',
            'check_read_count': 0,
            'grant': 'owner',
            'members': [],
            'invite': [],
            'created_at': '',
            'storages': [],
        },
        {
            'id': 39,
            'channel_id': 39,
            'domain': 'sandwich-tf',
            'name': '샌드위치 Team TF',
            'check_read_count': 0,
            'grant': 'owner',
            'members': [],
            'invite': [],
            'created_at': '',
            'storages': [],
        },
        {
            'id': 1,
            'channel_id': 1,
            'domain': 'planmakers',
            'name': '플랜메이커스',
            'check_read_count': 0,
            'grant': 'member',
            'members': [],
            'invite': [],
            'created_at': '',
            'storages': [],
        },
        {
            'id': 44,
            'channel_id': 44,
            'domain': 'metaverse',
            'name': '메타버스 프로젝트',
            'check_read_count': 0,
            'grant': 'member',
            'members': [],
            'invite': [],
            'created_at': '',
            'storages': [],
        },
        {
            'id': 8,
            'channel_id': 8,
            'domain': 'planiMX',
            'name': 'MX사업부',
            'check_read_count': 130,
            'grant': 'member',
            'members': [],
            'invite': [],
            'created_at': '',
            'storages': [],
        },
    ],
    setChannels: () => set((state) => ({ channels: state })),
}))
